### Broadcasting in NumPy

In [1]:
import numpy as np


### 1. Why Loops Are Slow
 In Python, loops are typically slow because:

* Python’s interpreter: Every iteration of the loop requires Python to interpret the loop logic, which is inherently slower than lower-level, compiled code.
* High overhead: Each loop iteration in Python involves additional overhead for function calls, memory access, and index management.

#### Looping Over Arrays in Python

In [3]:
arr  = np.array([1,2,3,4,5])
result = []

for num in arr:
    result.append(num**2)

print(result)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


#### Vectorization: Fixing the Loop Problem

In [4]:
arr = np.array([2,4,6,8,9])

result = arr**2 # vectorized operation 

print(result)

[ 4 16 36 64 81]


This is when you perform operations directly on arrays without explicit loops.

## Broadcasting in NumPy

####   Broadcasting: Scaling Arrays Without Extra Memory

* Broadcasting is the mechanism that allows NumPy to perform operations on arrays of different shapes.

* It “stretches” smaller arrays automatically without actually copying data.

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
arr2 = arr + 10 # SIMD concept is used ie Single instruction multiple Data 
# Stretches as [10,10,10,10,10,10,10,10,10,10]
# 10 is broadcast across the entire array 
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### 2D + 1D array

In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print(a + b) # b is stretched across rows:
"""[10 20 30]
[10 20 30]"""

[[11 22 33]
 [14 25 36]]


'[10 20 30]\n[10 20 30]'

- Two arrays are compatible if:

- Their dimensions are equal, OR
One of them is 1 in that dimension

### Normalizing Data Using Broadcasting

In [14]:
data = np.array([[10,20,30],
                 [15,25,35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]
                ])

In [17]:
mean = data.mean(axis=0)
mean

array([20., 30., 40.])

In [18]:
std = data.std(axis=0)
std

array([7.07106781, 7.07106781, 7.07106781])

In [19]:
normalized_data = (data - mean)/std

In [20]:
normalized_data

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])