### Data Types in NumPy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.astype("float64")

array([1., 2., 3., 4.])

In [7]:
arr.astype(np.int32)

array([1, 2, 3, 4], dtype=int32)

In [8]:
arr.nbytes

32

In [11]:
arrs = np.array(["nikash","lamsal","bct"],dtype='U10')
arr.dtype

dtype('int64')

### Complex numbers in numpy


In [9]:
arrc = np.array([1 + 2j , 3 + 4j ])
arrc.dtype

dtype('complex128')

### Object data type 

In [13]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']


## Summary
* NumPy arrays are homogeneous, meaning all elements must be of the same type.
* The choice of data type affects memory usage, performance, and precision.
* Be mindful of complex numbers and object data types, which can increase memory usage and reduce performance.