### Indexing and slicing


In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])

In [4]:
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

#### Indexing (Same as Python Lists)


In [5]:
flat[0]

np.int64(1)

In [9]:
flat[-2]

np.int64(10)

#### Slicing (Extracting Parts of an Array)


In [7]:
flat[2:4]

array([3, 4])

In [10]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [12]:
flat[5:] # flat[5:last]

array([ 6,  6,  7,  8,  9, 10, 11])

In [14]:
flat[::2] # every second element 

array([ 1,  3,  5,  6,  8, 10])

##### Slicing returns a view, not a copy! Changes affect the original array.**

#####  In NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

#### It's demo

In [15]:
flat

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [17]:
b = flat[0:3]
b

array([1, 2, 3])

In [19]:
b[1] = 98

In [20]:
b

array([ 1, 98,  3])

In [21]:
flat

array([ 1, 98,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

#### for copy

In [22]:
b = flat[1:4].copy() # this will make copy and slice wont work 

### 6. Fancy Indexing & Boolean Masking

In [23]:
flat

array([ 1, 98,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

##### Fancy Indexing (Select Multiple Elements)


In [24]:
flat[[0,1,2,3]]

array([ 1, 98,  3,  4])

In [28]:
idx = [0,3,5]

In [ ]:
flat[idx]

array([1, 4, 6])

: 

##### Boolean Masking (Filter Data)
