In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
np.mean(arr)

np.float64(5.0)

In [4]:
np.std(arr)

np.float64(2.581988897471611)

In [5]:
np.var(arr)

np.float64(6.666666666666667)

In [6]:
np.min(arr)

np.int64(1)

In [7]:
np.max(arr)

np.int64(9)

In [8]:
np.sum(arr)

np.int64(45)

In [9]:
np.prod(arr)

np.int64(362880)

In [10]:
np.median(arr)

np.float64(5.0)

In [11]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(5.0)

In [13]:
np.argmin(arr) #Return the index of the minimum value in an array.

np.int64(0)

In [14]:
np.argmax(arr) #Return the index of the maximum value in an array.

np.int64(8)

In [17]:
arr2 = np.array([9,8,7,6,5,4,3,2,1])
arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [19]:
np.corrcoef(arr1, arr2) #Compute the correlation coefficient matrix of two arrays.

array([[ 1., -1.],
       [-1.,  1.]])

In [20]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.cumsum(arr) # Compute the cumulative sum of an array.

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [23]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.log(arr)   #Compute the natural logarithm of an array.

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [25]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])