### Multidimensional Indexing and Axis

##### Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.


In [3]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* 1D array → 1 axis (axis 0)
* 2D array → 2 axes (axis 0 = rows, axis 1 = columns)
* 3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [6]:
arr[0]

array([1, 2, 3])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(np.sum(arr,axis=0)) #all row participate 

[12 15 18]


In [9]:
np.sum(arr,axis=1) # all column participate

array([ 6, 15, 24])

In [10]:
arr[0][0]

np.int64(1)

In [11]:
arr[0,1]

np.int64(2)

In [12]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 3. Indexing in 3D Arrays


In [24]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [25]:
arr.ndim # (depth , row , column )

3

In [26]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr.shape

(2, 2, 3)

#### Accessing elements in 3D:


In [ ]:
arr[1,0,0] # depth , row , index  ie 

np.int64(7)

In [35]:
np.sum(arr,axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [36]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr[0,0,0:3]


array([1, 2, 3])