In [2]:
import numpy as np

#### 1. Creating NumPy Arrays
##### From Python Lists:

In [12]:
arr1 = np.array([1,2,3,4,5]) # 1D array
arr1

array([1, 2, 3, 4, 5])

In [13]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]]) # 2D array
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

##### 🔹 Unlike lists, all elements must have the same data type.

#### Powerful shortcuts to create arrays without loops!

In [ ]:
np.zeros((3,4)) # 3x4 array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4)) # 3x4 array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.full((3,4),7)  # 2x2 array filled with 7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [22]:
np.eye(4)  # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(1,11,2) # [1, 3, 5, 7, 9] (like range)


array([1, 3, 5, 7, 9])

In [37]:
np.linspace(0,100,20) ## [0. 0.25 0.5 0.75 1.] (evenly spaced) and give 20 data  if not specified default space is 50 

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

#### 2. Checking Array Properties

In [40]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [41]:
myarr.shape

(3, 3)

In [42]:
myarr.size

9

In [43]:
myarr.ndim

2

In [47]:
myarr.dtype

dtype('int64')

In [46]:
hi = np.array([[[1,2],[3,4]],[[4,5],[6,7]]])  #3D array
hi.ndim

3

##### 🔹 NumPy arrays are strongly typed, meaning all elements share the same data type.

#### 3. Changing Data Types

In [ ]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float32') # Explicit type
myarr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
n = myarr.astype('float64') # Explicit type
m = myarr.astype(np.int64) # Explicit type
print(m.dtype)
print(n.dtype)

int64
float64



##### Efficient memory usage by choosing the right data type.


#### 4. Reshaping and Flattening Arrays


In [57]:
arr = np.array([[1,2,3],[3,4,5],[5,6,7],[8,9,0]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [8, 9, 0]])

In [55]:
arr.shape

(4, 3)

In [63]:
reshaped = arr.reshape((3,4))
reshaped

array([[1, 2, 3, 3],
       [4, 5, 5, 6],
       [7, 8, 9, 0]])

In [59]:
arr.size

12

In [68]:
flattened = arr.flatten() # convert nd to 1d

In [67]:
flattened

array([1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9, 0])