# Linear Alzebra
### 1. Matrix Operation

      A=[[2   -1], [​0    3​]]
      B=[[1   ​ 2], [-3   4​]]

* A + B
* AB
* 3A−2B

In [19]:
import numpy as np

A = np.array([[2,-1],[0,3]])
B = np.array([[1,2],[-3,4]])

sum = A + B
product = np.dot(A,B)
p = A@B
subtraction = 3 * A - 2 * B
print("multiplication :\n",p)
print("A + B: \n",sum)
print("AB: \n",product)
print("3A - 2B: \n",subtraction)


multiplocation :
 [[ 5  0]
 [-9 12]]
A + B: 
 [[ 3  1]
 [-3  7]]
AB: 
 [[ 5  0]
 [-9 12]]
3A - 2B: 
 [[ 4 -7]
 [ 6  1]]


### 2. Determinants and Inverses 
 * Find the determinant of A.


In [4]:
A = np.array([[2,-1],[0,3]])
det_A = np.linalg.det(A)
print("Determinant of A : ",det_A)

Determinant of A :  6.0


* Determine whether A is invertible. If yes, calculate A^-1.

In [10]:
a = det_A
if a != 0:
    A_inv = True
    print("Matrix A is invertible")
else:
    A_inv = False
    print("Matrix A is not invertible")
if A_inv:
    inv_A= np.linalg.inv(A)
    print("Invertible of A is :\n",inv_A)


Matrix A is invertible
Invertible of A is :
 [[0.5        0.16666667]
 [0.         0.33333333]]


### 3. Eigenvalues and Eigenvectors 
* Compute the eigenvalues and eigenvectors of the matrix:


      C=[[4  1], [​−2  1]​]

In [12]:
C = np.array([[4, 1], [-2, 1]])
eigenvalues, eigenvectors = np.linalg.eig(C)
print("Eigenvectors of C:\n", eigenvalues)
print("Eigenvectors of C:\n", eigenvectors)

Eigenvectors of C:
 [3. 2.]
Eigenvectors of C:
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


### 4. You are given a dataset of cars with the following features:
* Number of cylinders (x1​)
* Engine size in liters (x2​)
* Horsepower (x3)

### Car 1:
* x1: 4
* x2: 1.5
* x3: 100
* price: 20

### Car 2:
* x1: 6
* x2: 2.0
* x3: 150
* price: 30

### Car 3:
* x1: 8
* x2: 3.0
* x3: 200
* price: ?

In [17]:
X = np.array([[4, 1.5, 100], [6, 2.0, 150]])
y = np.array([20, 30])
beta = np.linalg.pinv(X.T @ X) @ X.T @ y
car_3 = np.array([8, 3.0, 200])
price_car_3 = car_3 @ beta
print("Estimated price of car 3:", price_car_3)


Estimated price of car 3: 39.99999999999998
